switch:
  - platform: template
    switches:
      dhw_circulation_switch:
        friendly_name: "DHW circulation switch (S3)" 
        turn_on:
          action: switch.turn_on
          target:
            entity_id: switch.shelly_plug_s3
        turn_off:
          action: switch.turn_off
          target:
            entity_id: switch.shelly_plug_s3

template:
  - binary_sensor: # State of shelly switche S3 for boiler circulation UFH 
      - name: "Therma V DHW circulation state (S3)"
        state: >
          {{ is_state('switch.shelly_plug_s3', 'on') }}

automation:
  - id: dhw_circulation_on_auto
    alias: dhw_circulation_on_auto
    description: Set the DHW circulation state to on
    mode: restart
    triggers:
      - trigger: state
        entity_id: binary_sensor.therma_v_dhw_heating_state
        to: 'on'
        for:
          minutes: 10
      - trigger: state
        entity_id: binary_sensor.therma_v_dhw_booster_state
        to: 'on'
        for:
          minutes: 20
      - trigger: state
        entity_id: binary_sensor.therma_v_dhw_booster_2_state_s1
        to: 'on'
        for:
          minutes: 20
    conditions:
      and:
        - condition: state
          entity_id: binary_sensor.therma_v_defrost_state
          state: 'off'
        - or:
          - condition: state
            entity_id: binary_sensor.therma_v_dhw_heating_state
            state: 'on'
          - condition: state
            entity_id: binary_sensor.therma_v_dhw_booster_state
            state: 'on'
          - condition: state
            entity_id: binary_sensor.therma_v_dhw_booster_2_state_s1
            state: 'on'
    actions:
      - action: switch.turn_on
        target:
            entity_id: switch.dhw_circulation_switch

  - id: dhw_circulation_off_auto
    alias: dhw_circulation_off_auto
    description: Set the DHW circulation state to off
    mode: restart
    triggers:
      - trigger: time_pattern
        minutes: "/5"
      - trigger: state
        entity_id: binary_sensor.therma_v_dhw_heating_state
      - trigger: state
        entity_id: binary_sensor.therma_v_dhw_booster_state
      - trigger: state
        entity_id: binary_sensor.therma_v_dhw_booster_2_state_s1
    conditions: 
      - condition: state
        entity_id: binary_sensor.therma_v_dhw_booster_state
        state: 'off'
      - condition: state
        entity_id: binary_sensor.therma_v_dhw_heating_state
        state: 'off'
      - condition: state
        entity_id: binary_sensor.therma_v_dhw_booster_2_state_s1
        state: 'off'
    actions:
      - action: switch.turn_off
        target:
          entity_id: switch.dhw_circulation_switch


