input_select:
  # Input select to switch between heatpump power saving regimes
  therma_v_ess_select:
    name: "Therma V energy state (H/C/DHW)"
    options:
      - "0 - Power saving state not used"
      - "1 - Forced off (unit locked)"
      - "2 - Normal operation (-/-/-)"
      - "3 - High power state (2/-/5)"
      - "4 - Very high DHW power state (-/-/80)"
      - "5 - Very high power state (2/2/10)"
      - "6 - High power state (1/1/5)"
      - "7 - Low power state (-/1/3)"
      - "8 - Very low power state (-/2/6)"
    initial: "0 - Power saving state not used"
    icon: mdi:state

input_number:
  # Input number to set the price difference that results in high price regime
  therma_v_ess_high_price_difference:
    name: "Therma V ESS high price difference"
#    initial: 0.07
    min: 0
    max: 1 
    step: 0.01 # 1ct accuracy 
    mode: box
    unit_of_measurement: "€"
    icon: mdi:cash-edit


automation:
  # Automation that deals with setting ESS for net negative energy prices
  - id: ess_based_on_e_price_negative_auto
    alias: "ESS based on e-price negative auto"
    description: Set the ESS state of the Therma V based on negative e-price
    mode: restart
    triggers:
      - trigger: time_pattern
        minutes: "/30"  # catch missed triggers
      - trigger: state
        entity_id: sensor.nord_pool_nl_current_prices_including_tax
    conditions:
      - condition: template
        value_template: "{{ (states('sensor.nord_pool_nl_current_prices_including_tax') | float(0) ) <= 0 }}"       
    actions:
      - delay:
          hours: 0
          minutes: 5
          seconds: 0
      - action: switch.turn_on
        target:
          entity_id: switch.therma_v_heating_cooling_on_off
      - action: switch.turn_on
        target:
          entity_id: switch.therma_v_dhw_on_off
      - action: input_boolean.turn_on
        target:
          entity_id: input_boolean.silent_mode_startup
      - choose:
        - conditions:
            - condition: numeric_state
              entity_id: sensor.current_percentage_of_energy_price
              below: 5
            - condition: template
              value_template: "{{ (states('sensor.nord_pool_nl_next_price') | float(0) ) >= (states('sensor.nord_pool_nl_current_price') | float(0) ) }}"   
          sequence:
            - action: input_select.select_option
              target:
                entity_id: input_select.therma_v_ess_select
              data:
                option: '{{ state_attr("input_select.therma_v_ess_select", "options")[ 5 ] }}' # Very high power state
        default:
          - action: input_select.select_option
            target:
              entity_id: input_select.therma_v_ess_select
            data:
              option: '{{ state_attr("input_select.therma_v_ess_select", "options")[ 6 ] }}' # High power state

  # Automation that deals with setting ESS for positive energy prices low price difference
  - id: ess_based_on_e_price_positive_normal_auto
    alias: "ESS based on e-price positive normal auto"
    description: Set the ESS state of the Therma V based on positive e-price low price difference
    mode: restart
    triggers:
      - trigger: time_pattern
        minutes: "/30"  # catch missed triggers
      - trigger: state
        entity_id: sensor.nord_pool_nl_current_prices_including_tax
      - trigger: state
        entity_id: binary_sensor.therma_v_dhw_heating_state
    conditions:
      - condition: template
        value_template: "{{ (states('sensor.nord_pool_nl_current_prices_including_tax') | float(0) ) > 0 }}"
      - condition: template
        value_template: "{{ (states('sensor.difference_in_electricity_price_today') | float(0) ) < (states('input_number.therma_v_ess_high_price_difference') | float(0)) }}"
    actions:
      - delay:
          hours: 0
          minutes: 5
          seconds: 0
      - choose:
          - conditions:
              - or:
                  - condition: numeric_state
                    entity_id: sensor.current_percentage_of_energy_price
                    below: 50
                  - condition: state
                    entity_id: binary_sensor.therma_v_dhw_heating_state
                    state: "on"
            sequence:
              - action: input_select.select_option
                target:
                  entity_id: input_select.therma_v_ess_select
                data:
                  option: '{{ state_attr("input_select.therma_v_ess_select", "options")[ 2 ] }}' # Normal power state also always during DHW run
        default:
          sequence:
            - action: input_select.select_option
              target:
                entity_id: input_select.therma_v_ess_select
              data:
                option: '{{ state_attr("input_select.therma_v_ess_select", "options")[ 7 ] }}' # Low power state

# Automation that deals with setting ESS for positive energy prices high price difference
  - id: ess_based_on_e_price_positive_high_auto
    alias: "ESS based on e-price positive high auto"
    description: Set the ESS state of the Therma V based on positive e-price high price difference
    mode: restart
    triggers:
      - trigger: time_pattern
        minutes: "/30"  # catch missed triggers
      - trigger: state
        entity_id: sensor.nord_pool_nl_current_prices_including_tax
      - trigger: state
        entity_id: binary_sensor.therma_v_dhw_heating_state
    conditions:
      - condition: template
        value_template: "{{ (states('sensor.nord_pool_nl_current_prices_including_tax') | float(0) ) > 0 }}"
      - condition: template
        value_template: "{{ (states('sensor.difference_in_electricity_price_today') | float(0) ) >= (states('input_number.therma_v_ess_high_price_difference') | float(0)) }}"
    actions:
      - delay:
          hours: 0
          minutes: 5
          seconds: 0
      - choose:
        - conditions:
            - condition: numeric_state
              entity_id: sensor.current_percentage_of_energy_price
              below: 5
            - condition: template
              value_template: "{{ (states('sensor.nord_pool_nl_next_price') | float(0) ) >= (states('sensor.nord_pool_nl_current_price') | float(0) ) }}"    
          sequence:
            - action: input_select.select_option
              target:
                entity_id: input_select.therma_v_ess_select
              data:
                option: '{{ state_attr("input_select.therma_v_ess_select", "options")[ 6 ] }}' # High power state
        - conditions:
            - condition: state
              entity_id: binary_sensor.therma_v_dhw_heating_state
              state: "on"
          sequence:
            - action: input_select.select_option
              target:
                entity_id: input_select.therma_v_ess_select
              data:
                option: '{{ state_attr("input_select.therma_v_ess_select", "options")[ 2 ] }}' # At least Normal ESS during DHW run
        - conditions:
            - condition: numeric_state
              entity_id: sensor.current_percentage_of_energy_price
              above: 50
          sequence:
            - action: input_select.select_option
              target:
                entity_id: input_select.therma_v_ess_select
              data:
                option: '{{ state_attr("input_select.therma_v_ess_select", "options")[ 8 ] }}' # Very low power state
        default:
          - action: input_select.select_option
            target:
              entity_id: input_select.therma_v_ess_select
            data:
              option: '{{ state_attr("input_select.therma_v_ess_select", "options")[ 7 ] }}' # low power state


  # Update function for ESS state. Sets input select based on HP state and vice verse
  - id: therma_v_update_energy_saving_state_auto
    alias: "Therma V Update Energy Saving State auto"
    description: Synchronizes the Therma V ESS input select and modbus state
    mode: single
    max_exceeded: silent
    triggers:
      - trigger: state
        entity_id:
          - sensor.therma_v_energy_state
        id: ess_modbus_trig
      - trigger: state
        entity_id:
          - input_select.therma_v_ess_select
        id: ess_select_trig
      - trigger: homeassistant
        event: start
        id: ess_ha_start_trig
    conditions: []
    actions:
      - choose:
        - conditions:
            - condition: trigger
              id: ess_modbus_trig
          sequence:
            - variables:
                index: '{{ trigger.to_state.state | int(0) }}'
            - action: input_select.select_option
              target:
                entity_id: input_select.therma_v_ess_select
              data:
                option: '{{ state_attr("input_select.therma_v_ess_select", "options")[ index ] }}'
        - conditions:
            - condition: trigger
              id: ess_select_trig
          sequence:
            - action: modbus.write_register
              data_template:
                address: 9
                slave: 1
                hub: modbus_gateway_therma_v
                value: '{{ trigger.to_state.state[0] | int(0)  }}'
        default:
          - variables:
              index: '{{ states("sensor.therma_v_energy_state") | int(0) }}'
          - action: input_select.select_option
            target:
              entity_id: input_select.therma_v_ess_select
            data:
              option: '{{ state_attr("input_select.therma_v_ess_select", "options")[ index ] }}'
            