input_datetime:
  start_time_electricity_lowest_hours:
    name: Start time electricity lowest hours
    has_date: false
    has_time: true

automation:
  # Plan low and high hours
  - id: plan_electricity_lowest_hours_auto
    alias: "Plan electricity highest and lowest hours auto"
    description: "Plan start moment of higest and lowest electricity price hours"
    mode: single
    triggers:
      - trigger: time
        at: "00:01" # every day just after midnight 
    actions:
          # start_highest_hours: >
          #   {% from 'cheapest_energy_hours.jinja' import cheapest_energy_hours %}
          #   {{ as_timestamp(cheapest_energy_hours( sensor='sensor.nord_pool_nl_current_prices_excluding_tax', attr_all='prices', time_key='time', value_key='price', use_hourly_avg=true, hours=(24-number_of_highest_hours), look_ahead=false, include_today=true, include_tomorrow=false, start='00:00', end='23:59')) }}
      - variables:
          number_of_lowest_hours: 1  # Peak and low hours
          start_lowest_hours: >
            {% from 'cheapest_energy_hours.jinja' import cheapest_energy_hours %}
            {{ cheapest_energy_hours( sensor='sensor.nord_pool_nl_current_prices_excluding_tax', attr_all='prices', time_key='time', value_key='price', use_hourly_avg=true, hours=number_of_lowest_hours,  look_ahead=false, include_today=true, include_tomorrow=false, start='00:00', end='23:59') }}
      # plan start lowest hours
      - action: input_datetime.set_datetime
        target:
          entity_id: input_datetime.start_time_electricity_lowest_hours
        data:
          datetime: "{{start_lowest_hours}}" 

template:
  - sensor:
    # Template sensor for prices including tax  
    - name: "Nord pool NL current prices Including Tax"
      unique_id: nord_pool_nl_current_prices_including_tax
      unit_of_measurement: "€/kWh"
      state_class: measurement
      state: >
        {% set cost = states('sensor.nord_pool_nl_current_price') | float(0) %}
        {% set zonneplan = 0.020 | float(0) %}
        {% set energy_tax  = 0.1088 | float(0) %}
        {% set VAT         = 0.21 | float(0) %}
        {{ ( (cost + zonneplan + energy_tax) * (1+VAT) ) | round(2, default=0) }}
      attributes:
        prices: >
          {% set zonneplan = 0.022 | float(0) %}
          {% set energy_tax  = 0.1088 | float(0) %}
          {% set VAT         = 0.21 | float(0) %}
          {% set energy_prices = state_attr('sensor.nord_pool_nl_current_prices_excluding_tax','prices') %}
          {% set ns = namespace(list=[]) %}
          {% for i in range(energy_prices|length) %}
          {%   set ns.list = ns.list+[{'time': energy_prices[i]['time'], 'price':( (energy_prices[i]['price']|float) + zonneplan + energy_tax)*(1+VAT)}] %}  
          {% endfor %}
          {{ ns.list }}

    # Template sensors for current hourly price
    - name: "Current hourly electricity price excluding tax"
      unit_of_measurement: "€"
      state_class: measurement
      availability: >
        {% set current = states('sensor.nord_pool_nl_current_prices_excluding_tax') | float("unknown") %}
        {{ current|is_number }}
      state: >
        {% from 'cheapest_energy_hours.jinja' import cheapest_energy_hours %}
        {% set current = cheapest_energy_hours( sensor='sensor.nord_pool_nl_current_prices_excluding_tax', attr_all='prices',time_key='time', value_key='price', mode='average', use_hourly_avg=true, hours='all', look_ahead=false, include_today=true, include_tomorrow=false, start=as_timestamp(now())|timestamp_custom('%H')+':00', end=as_timestamp(now())|timestamp_custom('%H')+':59') %}

        {{ current | round(3, default=0) }}

    - name: "Current hourly electricity price including tax"
      unit_of_measurement: "€"
      state_class: measurement
      availability: >
        {% set current = states('sensor.nord_pool_nl_current_prices_including_tax') | float("unknown") %}
        {{ current|is_number }}
      state: >
        {% from 'cheapest_energy_hours.jinja' import cheapest_energy_hours %}
        {% set current = cheapest_energy_hours( sensor='sensor.nord_pool_nl_current_prices_including_tax', attr_all='prices',time_key='time', value_key='price', mode='average', use_hourly_avg=true, hours='all', look_ahead=false, include_today=true, include_tomorrow=false, start=as_timestamp(now())|timestamp_custom('%H')+':00', end=as_timestamp(now())|timestamp_custom('%H')+':59') %}

        {{ current  | round(3, default=0) }}
        
    # Template sensors for current percentage of energy price
    - name: "Current percentage of electricity price"
      unit_of_measurement: "%"
      state_class: measurement
      availability: >
        {% set current = states('sensor.nord_pool_nl_current_prices_including_tax') | float("unknown") %}
        {{ current|is_number }}
      state: >
        {% from 'cheapest_energy_hours.jinja' import cheapest_energy_hours %}
        {% set high = cheapest_energy_hours( sensor='sensor.nord_pool_nl_current_prices_excluding_tax', attr_all='prices',time_key='time', value_key='price', mode='max', use_hourly_avg=true, hours='all', look_ahead=false, include_today=true, include_tomorrow=false) %}
        {% set low = cheapest_energy_hours( sensor='sensor.nord_pool_nl_current_prices_excluding_tax', attr_all='prices',time_key='time', value_key='price', mode='min', use_hourly_avg=true, hours='all', look_ahead=false, include_today=true, include_tomorrow=false) %}
        {% set current = cheapest_energy_hours( sensor='sensor.nord_pool_nl_current_prices_excluding_tax', attr_all='prices',time_key='time', value_key='price', mode='average', use_hourly_avg=true, hours='all', look_ahead=false, include_today=true, include_tomorrow=false, start=as_timestamp(now())|timestamp_custom('%H')+':00', end=as_timestamp(now())|timestamp_custom('%H')+':59') %}
        {# set current_old = states('sensor.nord_pool_nl_current_price') | float(0) #}
        {# set high_old    = states('sensor.nord_pool_nl_highest_price') | float(0) #}
        {# set low_old     = states('sensor.nord_pool_nl_lowest_price') | float(0) #}

        {{ ( (current-low)/(high-low) * 100 ) | round(1, default=0) }}

    # sensor that determines the e-price difference today
    - name: "Difference in electricity price today"
      state_class: measurement
      unit_of_measurement: '€'
      availability: >
        {% set current = states('sensor.nord_pool_nl_current_prices_including_tax') | float("unknown") %}
        {{ current|is_number }}
      state: >
        {% from 'cheapest_energy_hours.jinja' import cheapest_energy_hours %}
        {% set high = cheapest_energy_hours( sensor='sensor.nord_pool_nl_current_prices_excluding_tax', attr_all='prices',time_key='time', value_key='price', mode='max', use_hourly_avg=true, hours='all', look_ahead=false, include_today=true, include_tomorrow=false) %}
        {% set low = cheapest_energy_hours( sensor='sensor.nord_pool_nl_current_prices_excluding_tax', attr_all='prices',time_key='time', value_key='price', mode='min', use_hourly_avg=true, hours='all', look_ahead=false, include_today=true, include_tomorrow=false) %}
        
        {{ ( (high-low) )  | round(3) }}

    # sensor that determines the e-price difference today
    - name: "Start peak hours electricity price today"
      availability: >
        {% set current = states('sensor.nord_pool_nl_current_prices_including_tax') | float("unknown") %}
        {{ current|is_number }}
      state: >
        {% from 'cheapest_energy_hours.jinja' import cheapest_energy_hours %}
        {% set high = cheapest_energy_hours( sensor='sensor.nord_pool_nl_current_prices_excluding_tax', attr_all='prices',time_key='time', value_key='price', mode='max', use_hourly_avg=true, hours='all', look_ahead=false, include_today=true, include_tomorrow=false) %}
        {% set low = cheapest_energy_hours( sensor='sensor.nord_pool_nl_current_prices_excluding_tax', attr_all='prices',time_key='time', value_key='price', mode='min', use_hourly_avg=true, hours='all', look_ahead=false, include_today=true, include_tomorrow=false) %}
        
        {{ ( (high-low) )  | round(3) }}

    # Template sensors to determine the electricity cost per hour EURO/hr excl. tax
    - name: "Electric power cost per hour including tax"
      state_class: measurement
      unit_of_measurement: "€/h"
      availability: >
        {% set power   = states('sensor.p1_meter_3c39e72e6af0_active_power') | float("unknown") %}
        {% set cost    = states('sensor.nord_pool_nl_current_prices_including_tax') | float("unknown") %}
        {{ power|is_number and cost|is_number}}
      state: >
          {% set power   = states('sensor.p1_meter_3c39e72e6af0_active_power') | float(0) %}
          {% set cost    = states('sensor.nord_pool_nl_current_prices_including_tax') | float(0) %}
          {{ power/1000*cost }}
    # Template sensors to determine the electricity cost per hour EURO/hr incl. tax
    - name: "Electric power cost per hour excluding tax"
      state_class: measurement
      unit_of_measurement: "€/h"
      availability: >
        {% set power   = states('sensor.p1_meter_3c39e72e6af0_active_power') | float("unknown") %}
        {% set cost    = states('sensor.nord_pool_nl_current_price') | float("unknown") %}
        {{ power|is_number and cost|is_number}}
      state: >
          {% set power   = states('sensor.p1_meter_3c39e72e6af0_active_power') | float(0) %}
          {% set cost    = states('sensor.nord_pool_nl_current_price') | float(0) %}
          {{ power/1000*cost }}

  # Triggered Nord Pool price gathering in attributes excluding tax
  - trigger:
      - platform: state
        entity_id: sensor.nord_pool_nl_current_price
      - platform: homeassistant
        event: start
    action:
      - action: nordpool.get_prices_for_date
        response_variable: energyprices
        data:
          config_entry: !secret nord_pole_config_entry
          date: "{{ now().date() + timedelta(days=0) }}"
          areas: NL
          currency: EUR
    sensor:
      name: Nord pool NL current prices Excluding Tax
      unique_id: nord_pool_nl_current_prices_excluding_tax
      unit_of_measurement: "€/kWh"
      state: >
        {{ states('sensor.nord_pool_nl_current_price') | float(0) }}
      attributes:
        prices: >
          {% set energy_prices = energyprices['NL'] %}
          {% set ns = namespace(list=[]) %}
          {% for i in range(energy_prices|length) %}
          {%   set ns.list = ns.list+[{'time': energy_prices[i]['start'], 'price':((energy_prices[i]['price']|float)/1000)}] %}  
          {% endfor %}
          {{ ns.list }}


  # triggered sensors for the total energy cost per day based on the statistics sensors
  - trigger:
    - trigger: time_pattern
      hours: 0
      minutes: 0
    sensor:
      - name: "Energy cost per day including tax"
        state_class: measurement
        unit_of_measurement: "€"
        state: "{{ states('sensor.energy_cost_over_one_day_including_tax')|float(0) }}"
  - trigger:
    - trigger: time_pattern
      hours: 0
      minutes: 0
    sensor:
      - name: "Energy cost per day excluding tax"
        state_class: measurement
        unit_of_measurement: "€"
        state: "{{ states('sensor.energy_cost_over_one_day_excluding_tax')|float(0) }}"

sensor:
  # integration of Euro/hr result is Euros
  - platform: integration
    source: sensor.electric_power_cost_per_hour_including_tax
    name: "Energy cost including tax"
    method: left
    unit_time: h
    round: 2
  - platform: integration
    source: sensor.electric_power_cost_per_hour_excluding_tax
    name: "Energy cost excluding tax"
    method: left
    unit_time: h
    round: 2
  # moving difference over 24hrs used for template sensors that trigger at 0:00
  # utility meters cycle and cannot be used reliably with the triggers in the template sensors
  - platform: statistics
    name: Energy cost over one day including tax
    entity_id: sensor.energy_cost_including_tax
    state_characteristic: change
    max_age:
      hours: 24
    precision: 2
    unique_id: energy_cost_over_one_day_including_tax

  - platform: statistics
    name: Energy cost over one day excluding tax
    entity_id: sensor.energy_cost_excluding_tax
    state_characteristic: change
    max_age:
      hours: 24
    precision: 2
    unique_id: energy_cost_over_one_day_excluding_tax

# The utility meters cycle daily automatically 
utility_meter:
  daily_energy_cost_including_tax:
    source: sensor.energy_cost_including_tax
    name: "Daily energy cost including tax"
    cycle: daily
#    delta_values: true #input is delta energy
    net_consumption: true #allows negative power
  daily_energy_cost_excluding_tax:
    source: sensor.energy_cost_excluding_tax
    name: "Daily energy cost excluding tax"
    cycle: daily
#    delta_values: true # input is delta energy
    net_consumption: true #allows negative power