input_select:
  goodwe_export_strategy_select:
    name: "Goodwe grid export strategy"
    options:
      - "0 - Manual"
      - "1 - Maximum (zero export with net negative prices)"
      - "2 - Balanced (ratiomatic export with gross negative prices)"
      - "3 - Minimum (zero om meter with gross negative prices)"
      - "4 - No (zero on meter)"
    initial: "2 - Balanced (ratiomatic export with gross negative prices)"
    icon: mdi:sun-compass

automation:
  - id: update_goodwe_auto # Manual pollig at lower frequency, more reliable. 
    alias: "Goodwe data polling"
    mode: restart
    max_exceeded: silent
    triggers:
      - trigger: time_pattern
        minutes: "/3"
      - trigger: homeassistant
        event: start
    actions:
      - action: homeassistant.update_entity
        target:
          entity_id: sensor.pv_power

  - id: e_price_negative_goodwe_auto # Adjust grid export limit to 0 when prices are negative
    alias: e_price_negative_goodwe_auto
    description: Set inverter grid_limit to 0% when E-price is negative, E-price from ENTSO-e corrected to incl tax
    mode: restart
    triggers:
      # - trigger: state
      #   entity_id: sensor.inverter_temperature
      - trigger: time_pattern
        # minutes: "/3"
        seconds: "/42"
    conditions: 
      - condition: template
        value_template: "{{ not is_state('number.goodwe_grid_export_limit', 'unavailable') }}"
      - condition: template
        value_template: "{{ not is_state('number.goodwe_grid_export_limit', 'unknown') }}"
      - condition: template
        value_template: "{{ not is_state('sensor.pv_power', 'unavailable') }}"
      - condition: template
        value_template: "{{ not is_state('sensor.pv_power', 'unknown') }}"
      - condition: template
        value_template: "{{ not is_state('input_select.goodwe_export_strategy_select', state_attr('input_select.goodwe_export_strategy_select', 'options')[ 0 ] ) }}"
    actions:
      - variables:
          zero_on_meter: "{{ max(min( (states('number.goodwe_grid_export_limit') | float(0)) + 0.8*100/8000*(states('sensor.p1_meter_active_power_filtered') | float(0)) ,100),0) }}"
          balanced_max:  "{{ max(min( 100.0 - 100.0*(states('sensor.entsoe_apex_ex_current_electricity_market_price') | float(0) | abs) / ((states('sensor.entsoe_apex_in_current_electricity_market_price') | float(0) | abs) + (states('sensor.entsoe_apex_ex_current_electricity_market_price') | float(0) | abs)) ,100),2)  }}" 
      - choose:
          - conditions: # ZERO ON INC NEGATIVE
              - condition: numeric_state
                entity_id: sensor.entsoe_apex_in_current_electricity_market_price
                below: 0
            sequence:
              - action: number.set_value
                target:
                  entity_id: number.goodwe_grid_export_limit
                data:
                  value: 0.0
          - conditions: # MAXIMUM EXPORT
              - condition: template
                value_template: "{{ is_state('input_select.goodwe_export_strategy_select', state_attr('input_select.goodwe_export_strategy_select', 'options')[ 1 ] ) }}"
              - condition: numeric_state
                entity_id: sensor.entsoe_apex_ex_current_electricity_market_price
                below: 0.0
            sequence:
              - action: number.set_value
                target:
                  entity_id: number.goodwe_grid_export_limit
                data:
                  value: 100
          - conditions: # BALANCED EXPORT
              - condition: template
                value_template: "{{ is_state('input_select.goodwe_export_strategy_select', state_attr('input_select.goodwe_export_strategy_select', 'options')[ 2 ] ) }}"
              - condition: numeric_state
                entity_id: sensor.entsoe_apex_ex_current_electricity_market_price
                below: 0.0
            sequence:
              - action: number.set_value
                target:
                  entity_id: number.goodwe_grid_export_limit
                data:
                  value: "{{ max(balanced_max,zero_on_meter) | round(0) }}"
          - conditions: # MINIMUM EXPORT OR NO EXPORT
              - condition: or
                conditions: 
                  - condition: and
                    conditions: # MINIMUM EXPORT
                      - condition: template
                        value_template: "{{ is_state('input_select.goodwe_export_strategy_select', state_attr('input_select.goodwe_export_strategy_select', 'options')[ 3 ] ) }}"
                      - condition: numeric_state
                        entity_id: sensor.entsoe_apex_ex_current_electricity_market_price
                        below: 0.0
                  - condition: template # NO EXPORT
                    value_template: "{{ is_state('input_select.goodwe_export_strategy_select', state_attr('input_select.goodwe_export_strategy_select', 'options')[ 4 ] ) }}"
            sequence:
              - action: number.set_value
                target:
                  entity_id: number.goodwe_grid_export_limit
                data:
                  value: "{{ zero_on_meter | round(0) }}"
        default:
          - action: number.set_value
            target:
              entity_id: number.goodwe_grid_export_limit
            data:
              value: 100

  - id: goodwe_grid_export_limit_check_auto # Restart integration when grid export limit becomes unavailable
    alias: "Goodwe grid export limit check"
    description: Restart Goodwe integration when grid export limit is unavailable
    mode: single
    triggers:
      - trigger: time_pattern
        hours: "/1"
    conditions:
      - condition: or
        conditions:
          - condition: template
            value_template: "{{ is_state('number.goodwe_grid_export_limit', 'unavailable') }}"        
          - condition: template
            value_template: "{{ is_state('number.goodwe_grid_export_limit', 'unknown') }}"
      - condition: template
        value_template: "{{ not is_state('sensor.pv_power', 'unavailable') }}"
      - condition: template
        value_template: "{{ not is_state('sensor.pv_power', 'unknown') }}"
    actions:
      - action: homeassistant.reload_config_entry
        target:
          entity_id: number.goodwe_grid_export_limit

      # - condition: not
      #   conditions:
          # - condition: state
          #   entity_id: input_select.goodwe_export_strategy_select
          #   state: "0 - Manual" # NOT MANUAL


sensor:
  - platform: filter
    name: "P1 meter active power filtered"
    entity_id: sensor.p1_meter_3c39e72e6af0_active_power
    filters:
      - filter: lowpass
        time_constant: 10
