switch:
  # Template switch to used by the automationsas as state memory
  # seperately from the real state of the relay which can be switched manually too
  - platform: template
    switches:
      dhw_circulation_switch:
        friendly_name: "DHW circulation switch (S3)" 
        turn_on:
          action: switch.turn_on
          target:
            entity_id: switch.shelly_plug_s3
        turn_off:
          action: switch.turn_off
          target:
            entity_id: switch.shelly_plug_s3

template:
  # State of shelly switche S3 for DHW circulation pump
  # The circulation pump is for a vertical water tank to have more
  # equal heating during disinfection cycles and heating cycles
  - binary_sensor: 
      - name: "Therma V DHW circulation state (S3)"
        state: >
          {{ is_state('switch.shelly_plug_s3', 'on') }}

automation:
  # Switch on the circulation pump during long heating cycles and 
  # when the DHW heater has been turned on for a while
  - id: dhw_circulation_on_auto
    alias: "DHW circulation on auto"
    description: Set the DHW circulation state to on
    mode: restart
    triggers:
      - trigger: state
        entity_id: binary_sensor.therma_v_dhw_heating_state
        to: 'on'
        for:
          minutes: 10
      - trigger: state
        entity_id: binary_sensor.therma_v_dhw_booster_state
        to: 'on'
        for:
          minutes: 20
      - trigger: state
        entity_id: binary_sensor.therma_v_dhw_booster_2_state_s1
        to: 'on'
        for:
          minutes: 20
    conditions:
      and:
        - condition: state
          entity_id: binary_sensor.therma_v_defrost_state
          state: 'off'
        - or:
          - condition: state
            entity_id: binary_sensor.therma_v_dhw_heating_state
            state: 'on'
          - condition: state
            entity_id: binary_sensor.therma_v_dhw_booster_state
            state: 'on'
          - condition: state
            entity_id: binary_sensor.therma_v_dhw_booster_2_state_s1
            state: 'on'
    actions:
      - action: switch.turn_on
        target:
            entity_id: switch.dhw_circulation_switch

  - id: dhw_circulation_off_auto
    # Switch off the circulation after heating (HP or heater by heatpump or relay)
    # This is also triggered every X minutes to make it robust for HA reboots
    alias: dhw_circulation_off_auto
    description: Set the DHW circulation state to off
    mode: restart
    triggers:
      - trigger: time_pattern
        minutes: "/5"
      - trigger: state
        entity_id: binary_sensor.therma_v_dhw_heating_state
      - trigger: state
        entity_id: binary_sensor.therma_v_dhw_booster_state
      - trigger: state
        entity_id: binary_sensor.therma_v_dhw_booster_2_state_s1
    conditions: 
      - condition: state
        entity_id: binary_sensor.therma_v_dhw_booster_state
        state: 'off'
      - condition: state
        entity_id: binary_sensor.therma_v_dhw_heating_state
        state: 'off'
      - condition: state
        entity_id: binary_sensor.therma_v_dhw_booster_2_state_s1
        state: 'off'
    actions:
      - action: switch.turn_off
        target:
          entity_id: switch.dhw_circulation_switch


