# ==============================================================================
# 1. HELPERS (BRUG NAAR SECRETS)
# ==============================================================================
# Note nu staan de secets in de state data!!!!! Gebruik dus niets wat je niet
# op straat wilt hebben. Maar op github kan niemand het lezen en het werkt wel
# in templates 
input_text:
  sessy_url:
    name: "Sessy URL/IP"
    initial: !secret sessy_url # Verwijst naar je IP (bijv: 192.168.1.100)

  sessy_auth:
    name: "Sessy Auth String"
    initial: !secret sessy_auth # Verwijst naar je inloggegevens (admin:wachtwoord)


# ==============================================================================
# 2. REST SENSOREN (HAAL DATA OP VAN DE SESSY)
# ==============================================================================
sensor:
  # REST SENSOR 1: Haalt de actieve strategie op (voor dashboard synchronisatie)
  - platform: rest
    name: "Sessy Active Strategy"
    unique_id: sessy_active_strategy
    method: GET
    resource_template: "http://{{ states('input_text.sessy_url') }}/api/v1/power/active_strategy"
    headers:
      Authorization: "Basic {{ states('input_text.sessy_auth') | base64_encode }}"
    value_template: "{{ value_json.strategy }}"
    scan_interval: 15

  # REST SENSOR 2: Haalt de uitgebreide EOL/NS JSON op (om attributen uit te splitsen)
  - platform: rest
    name: "Sessy EOL NS Data"
    unique_id: sessy_eol_ns_data
    method: GET
    resource_template: "http://{{ states('input_text.sessy_url') }}/api/v1/eol/ns"
    headers:
      Authorization: "Basic {{ states('input_text.sessy_auth') | base64_encode }}"
    value_template: "{{ value_json.driver_state }}"
    json_attributes:
      - network_switch
      - inverters
    scan_interval: 15

  # REST SENSOR 3: Haalt de /api/v2/power/status JSON op (om attributen uit te splitsen)
  - platform: rest
    name: "Sessy power status data"
    unique_id: sessy_pover_status_data
    method: GET
    resource_template: "http://{{ states('input_text.sessy_url') }}/api/v2/power/status"
    headers:
      Authorization: "Basic {{ states('input_text.sessy_auth') | base64_encode }}"
    value_template: "{{ value_json.status }}"
    json_attributes:
      - sessy
      - grid
      - solar
    scan_interval: 15

# Energy
  - platform: integration
    name: "Sessy Total Discharged Energy"
    unique_id: sessy_total_discharged_energy
    source: sensor.sessy_grid_total_discharging_power 
    method: left
    unit_prefix: k
    unit_time: h
    round: 2

  - platform: integration
    name: "Sessy Total Charged Energy"
    unique_id: sessy_total_charged_energy
    source: sensor.sessy_grid_total_charging_power
    method: left
    unit_prefix: k
    unit_time: h
    round: 2


template:
  - sensor:
      # ========================================================================
      # NETWORK SWITCH 
      # ========================================================================

      - name: "Sessy NS errors"
        unique_id: sessy_network_switch_errors
        state: "{{ state_attr('sensor.sessy_eol_ns_data', 'network_switch')['errors'] | int(0) }}"
        state_class: measurement

      - name: "Sessy NS warnings"
        unique_id: sessy_network_switch_warnings
        state: "{{ state_attr('sensor.sessy_eol_ns_data', 'network_switch')['warnings'] | int(0) }}"
        state_class: measurement

      ## ALSO IN /api/v2/power/status
      # - name: "Sessy grid frequency"
      #   unique_id: sessy_grid_frequency
      #   state: "{{ (state_attr('sensor.sessy_eol_ns_data', 'network_switch')['frequency'] / 1000) | round(2) }}"
      #   unit_of_measurement: "Hz"
      #   device_class: frequency
      #   state_class: measurement

      # - name: "Sessy grid voltage L1"
      #   unique_id: sessy_grid_voltage_l1
      #   state: "{{ (state_attr('sensor.sessy_eol_ns_data', 'network_switch')['phase_1'] / 1000) | round(1) }}"
      #   unit_of_measurement: "V"
      #   device_class: voltage
      #   state_class: measurement

      # - name: "Sessy grid voltage L2"
      #   unique_id: sessy_grid_voltage_l2
      #   state: "{{ (state_attr('sensor.sessy_eol_ns_data', 'network_switch')['phase_2'] / 1000) | round(1) }}"
      #   unit_of_measurement: "V"
      #   device_class: voltage
      #   state_class: measurement

      # - name: "Sessy grid voltage L3"
      #   unique_id: sessy_grid_voltage_l3
      #   state: "{{ (state_attr('sensor.sessy_eol_ns_data', 'network_switch')['phase_3'] / 1000) | round(1) }}"
      #   unit_of_measurement: "V"
      #   device_class: voltage
      #   state_class: measurement


      # ========================================================================
      # OMVORMER 1 (INVERTER_L1) -> INDEX 0
      # ========================================================================
      - name: "Sessy INV L1 active power"
        unique_id: sessy_l1_active_power
        state: "{{ state_attr('sensor.sessy_eol_ns_data', 'inverters')[0]['active_power'] }}"
        unit_of_measurement: "W"
        device_class: power
        state_class: measurement

      - name: "Sessy INV L1 apparent power"
        unique_id: sessy_l1_apparent_power
        state: "{{ state_attr('sensor.sessy_eol_ns_data', 'inverters')[0]['apparent_power'] | int(0) }}"
        unit_of_measurement: "VA"
        device_class: apparent_power
        state_class: measurement

      - name: "Sessy INV L1 DClink voltage"
        unique_id: sessy_l1_dc_link_voltage
        state: "{{ (state_attr('sensor.sessy_eol_ns_data', 'inverters')[0]['dc_link_voltage'] / 1000) | round(2) }}"
        unit_of_measurement: "V"
        device_class: voltage
        state_class: measurement

      - name: "Sessy INV L1 battery voltage"
        unique_id: sessy_l1_battery_voltage
        state: "{{ (state_attr('sensor.sessy_eol_ns_data', 'inverters')[0]['battery_voltage'] / 1000) | round(2) }}"
        unit_of_measurement: "V"
        device_class: voltage
        state_class: measurement

      - name: "Sessy INV L1 AC/DC temperature"
        unique_id: sessy_l1_ac_dc_temp
        state: "{{ (state_attr('sensor.sessy_eol_ns_data', 'inverters')[0]['ac_dc_temperature'] / 1000) | round(1) }}"
        unit_of_measurement: "°C"
        device_class: temperature
        state_class: measurement

      - name: "Sessy INV L1 DC/DC temperature"
        unique_id: sessy_l1_dc_dc_temp
        state: "{{ (state_attr('sensor.sessy_eol_ns_data', 'inverters')[0]['dc_dc_temperature'] / 1000) | round(1) }}"
        unit_of_measurement: "°C"
        device_class: temperature
        state_class: measurement

      - name: "Sessy INV L1 errors"
        unique_id: sessy_l1_errors
        state: "{{ state_attr('sensor.sessy_eol_ns_data', 'inverters')[0]['errors'] | int(0) }}"
        state_class: measurement

      - name: "Sessy INV L1 warnings"
        unique_id: sessy_l1_warnings
        state: "{{ state_attr('sensor.sessy_eol_ns_data', 'inverters')[0]['warnings'] | int(0) }}"
        state_class: measurement

      # ========================================================================
      # OMVORMER 2 (INVERTER_L2) -> INDEX 1
      # ========================================================================
      - name: "Sessy INV L2 active power"
        unique_id: sessy_l2_active_power
        state: "{{ state_attr('sensor.sessy_eol_ns_data', 'inverters')[1]['active_power'] }}"
        unit_of_measurement: "W"
        device_class: power
        state_class: measurement

      - name: "Sessy INV L2 apparent power"
        unique_id: sessy_l2_apparent_power
        state: "{{ state_attr('sensor.sessy_eol_ns_data', 'inverters')[1]['apparent_power'] | int(0) }}"
        unit_of_measurement: "VA"
        device_class: apparent_power
        state_class: measurement

      - name: "Sessy INV L2 DC link voltage"
        unique_id: sessy_l2_dc_link_voltage
        state: "{{ (state_attr('sensor.sessy_eol_ns_data', 'inverters')[1]['dc_link_voltage'] / 1000) | round(2) }}"
        unit_of_measurement: "V"
        device_class: voltage
        state_class: measurement

      - name: "Sessy INV L2 battery voltage"
        unique_id: sessy_l2_battery_voltage
        state: "{{ (state_attr('sensor.sessy_eol_ns_data', 'inverters')[1]['battery_voltage'] / 1000) | round(2) }}"
        unit_of_measurement: "V"
        device_class: voltage
        state_class: measurement

      - name: "Sessy INV L2 AC/DC temperature"
        unique_id: sessy_l2_ac_dc_temp
        state: "{{ (state_attr('sensor.sessy_eol_ns_data', 'inverters')[1]['ac_dc_temperature'] / 1000) | round(1) }}"
        unit_of_measurement: "°C"
        device_class: temperature
        state_class: measurement

      - name: "Sessy INV L2 DC/DC temperature"
        unique_id: sessy_l2_dc_dc_temp
        state: "{{ (state_attr('sensor.sessy_eol_ns_data', 'inverters')[1]['dc_dc_temperature'] / 1000) | round(1) }}"
        unit_of_measurement: "°C"
        device_class: temperature
        state_class: measurement

      - name: "Sessy INV L2 errors"
        unique_id: sessy_l2_errors
        state: "{{ state_attr('sensor.sessy_eol_ns_data', 'inverters')[1]['errors'] | int(0) }}"
        state_class: measurement

      - name: "Sessy INV L2 warnings"
        unique_id: sessy_l2_warnings
        state: "{{ state_attr('sensor.sessy_eol_ns_data', 'inverters')[1]['warnings'] | int(0) }}"
        state_class: measurement

      # ========================================================================
      # OMVORMER 3 (INVERTER_L3) -> INDEX 2
      # ========================================================================
      - name: "Sessy INV L3 active power"
        unique_id: sessy_l3_active_power
        state: "{{ state_attr('sensor.sessy_eol_ns_data', 'inverters')[2]['active_power'] }}"
        unit_of_measurement: "W"
        device_class: power
        state_class: measurement

      - name: "Sessy INV L3 apparent power"
        unique_id: sessy_l3_apparent_power
        state: "{{ state_attr('sensor.sessy_eol_ns_data', 'inverters')[2]['apparent_power'] | int(0) }}"
        unit_of_measurement: "VA"
        device_class: apparent_power
        state_class: measurement

      - name: "Sessy INV L3 DC link voltage"
        unique_id: sessy_l3_dc_link_voltage
        state: "{{ (state_attr('sensor.sessy_eol_ns_data', 'inverters')[2]['dc_link_voltage'] / 1000) | round(2) }}"
        unit_of_measurement: "V"
        device_class: voltage
        state_class: measurement

      - name: "Sessy INV L3 battery voltage"
        unique_id: sessy_l3_battery_voltage
        state: "{{ (state_attr('sensor.sessy_eol_ns_data', 'inverters')[2]['battery_voltage'] / 1000) | round(2) }}"
        unit_of_measurement: "V"
        device_class: voltage
        state_class: measurement

      - name: "Sessy INV L3 AC/DC temperature"
        unique_id: sessy_l3_ac_dc_temp
        state: "{{ (state_attr('sensor.sessy_eol_ns_data', 'inverters')[2]['ac_dc_temperature'] / 1000) | round(1) }}"
        unit_of_measurement: "°C"
        device_class: temperature
        state_class: measurement

      - name: "Sessy INV L3 DC/DC temperature"
        unique_id: sessy_l3_dc_dc_temp
        state: "{{ (state_attr('sensor.sessy_eol_ns_data', 'inverters')[2]['dc_dc_temperature'] / 1000) | round(1) }}"
        unit_of_measurement: "°C"
        device_class: temperature
        state_class: measurement

      - name: "Sessy INV L3 errors"
        unique_id: sessy_l3_errors
        state: "{{ state_attr('sensor.sessy_eol_ns_data', 'inverters')[2]['errors'] | int(0) }}"
        state_class: measurement

      - name: "Sessy INV L3 warnings"
        unique_id: sessy_l3_warnings
        state: "{{ state_attr('sensor.sessy_eol_ns_data', 'inverters')[2]['warnings'] | int(0) }}"
        state_class: measurement


      # ========================================================================
      # POWER STATUS
      # ========================================================================
      - name: "Sessy Battery State of Charge"
        unique_id: sessy_battery_state_of_charge
        state: "{{ state_attr('sensor.sessy_power_status_data', 'sessy').state_of_charge }}"
        unit_of_measurement: "%"
        device_class: battery
        state_class: measurement

      - name: "Sessy Battery Pack Voltage"
        unique_id: sessy_battery_pack_voltage
        state: "{{ (state_attr('sensor.sessy_power_status_data', 'sessy').pack_voltage / 1000) | round(2) }}"
        unit_of_measurement: "V"
        device_class: voltage
        state_class: measurement

      # 0. Total power
      - name: "Sessy Grid Total Power"
        unique_id: sessy_grid_total_power
        state: "{{ state_attr('sensor.sessy_power_status_data', 'sessy').total_power }}"
        unit_of_measurement: "W"
        device_class: power
        state_class: measurement

      # 1. Only discharging power, for Riemann integral
      - name: "Sessy Grid Total Discharging Power"
        unit_of_measurement: "W"
        device_class: power
        state: >
          {% set power = states('sensor.sessy_grid_total_power') | float(0) %}
          {{ power if power > 0 else 0 }}

      # 2. Only charging power, for Riemann integral
      - name: "Sessy Grid Total Charging Power"
        unit_of_measurement: "W"
        device_class: power
        state: >
          {% set power = states('sensor.sessy_grid_total_power') | float(0) %}
          {{ (power | abs) if power < 0 else 0 }}

      # Grid frequency
      - name: "Sessy Grid Frequency"
        unique_id: sessy_grid_frequency
        state: "{{ (state_attr('sensor.sessy_power_status_data', 'grid').frequency / 1000) | round(2) }}"
        unit_of_measurement: "Hz"
        device_class: frequency
        state_class: measurement

      # Grid voltage per phase
      - name: "Sessy Grid Voltage L1"
        unique_id: sessy_grid_voltage_l1
        state: "{{ (state_attr('sensor.sessy_power_status_data', 'grid').phase_voltage[0] / 1000) | round(1) }}"
        unit_of_measurement: "V"
        device_class: voltage
        state_class: measurement

      - name: "Sessy Grid Voltage L2"
        unique_id: sessy_grid_voltage_l2
        state: "{{ (state_attr('sensor.sessy_power_status_data', 'grid').phase_voltage[1] / 1000) | round(1) }}"
        unit_of_measurement: "V"
        device_class: voltage
        state_class: measurement

      - name: "Sessy Grid Voltage L3"
        unique_id: sessy_grid_voltage_l3
        state: "{{ (state_attr('sensor.sessy_power_status_data', 'grid').phase_voltage[2] / 1000) | round(1) }}"
        unit_of_measurement: "V"
        device_class: voltage
        state_class: measurement

      # Inverter power per phase
      - name: "Sessy Inverter Power L1"
        unique_id: sessy_inverter_power_l1
        state: "{{ state_attr('sensor.sessy_power_status_data', 'sessy').inverters.power[0] }}"
        unit_of_measurement: "W"
        device_class: power
        state_class: measurement

      - name: "Sessy Inverter Power L2"
        unique_id: sessy_inverter_power_l2
        state: "{{ state_attr('sensor.sessy_power_status_data', 'sessy').inverters.power[1] }}"
        unit_of_measurement: "W"
        device_class: power
        state_class: measurement

      - name: "Sessy Inverter Power L3"
        unique_id: sessy_inverter_power_l3
        state: "{{ state_attr('sensor.sessy_power_status_data', 'sessy').inverters.power[2] }}"
        unit_of_measurement: "W"
        device_class: power
        state_class: measurement

      # Solar PV Power per phase
      - name: "Sessy Solar PV Power L1"
        unique_id: sessy_solar_pv_power_l1
        state: "{{ state_attr('sensor.sessy_power_status_data', 'solar').pv_power[0] }}"
        unit_of_measurement: "W"
        device_class: power
        state_class: measurement

      - name: "Sessy Solar PV Power L2"
        unique_id: sessy_solar_pv_power_l2
        state: "{{ state_attr('sensor.sessy_power_status_data', 'solar').pv_power[1] }}"
        unit_of_measurement: "W"
        device_class: power
        state_class: measurement

      - name: "Sessy Solar PV Power L3"
        unique_id: sessy_solar_pv_power_l3
        state: "{{ state_attr('sensor.sessy_power_status_data', 'solar').pv_power[2] }}"
        unit_of_measurement: "W"
        device_class: power
        state_class: measurement