# Set silent mode time interval
input_datetime:
  silent_start_time: # start time of silent mode add to UI
    name: Silent mode start time
    has_date: false
    has_time: true
  silent_stop_time: # stop time of silent mode add to UI
    name: Silent mode stop time
    has_date: false
    has_time: true

template:
  # Switch which acts as state memory for the automations to enable silent mode
  - switch:
#      - state: "{{ is_state('switch.therma_v_silent_mode', 'on') }}"
#        availability: "{{ has_value('switch.therma_v_silent_mode') }}" 
      - name: silent_mode_state
        turn_on:
          action: switch.turn_on
          target:
            entity_id: switch.therma_v_silent_mode
        turn_off:
          action: switch.turn_off
          target:
            entity_id: switch.therma_v_silent_mode

# Extra input which acts as state memory for silent mode at start-up
input_boolean:
  silent_mode_startup:
    name: "Silent Mode at Startup" 

automation:
  - id: therma_v_silent_on_refrigirant_temp_time_based_auto
    alias: "Therma V Silent ON refrigirant temp time based auto"
    description: "Turns on silent mode when outside temp is above freezing and within silent window"
    mode: single
    max_exceeded: silent
    triggers: # Time trigger to ensure that silent mode recovers to a safe state
      - trigger: time
        at: input_datetime.silent_start_time
      - trigger: numeric_state
        entity_id: sensor.therma_v_refrigirant_temperature_suction
        above: 0
        for: "00:15:00"
    conditions:
      - and:
        - condition: state
          entity_id: switch.therma_v_heating_cooling_on_off
          state: 'on' # Allow only when heating is on! otherwise RMC may crash
        - or: # When time is within window or silent mode is on
          - condition: time 
            after: input_datetime.silent_start_time
            before: input_datetime.silent_stop_time
          - condition: state
            entity_id: switch.silent_mode_state
            state: 'on' # Allow only when silent mode state is on
    actions:
      - action: switch.turn_on
        target:
          entity_id: switch.therma_v_silent_mode

  - id: therma_v_silent_off_temp_time_based_auto
    alias: "Therma V Silent OFF temp time based auto"
    description: "Turns off silent mode respecting silent time window and temperature"
    mode: single
    max_exceeded: silent
    triggers: # Time trigger to ensure that silent mode recovers to a safe state
      - trigger: time
        at: input_datetime.silent_stop_time
      - trigger: numeric_state
        id: temp_trig
        entity_id: sensor.therma_v_refrigirant_temperature_suction
        below: 0
        for: "00:05:00"
    conditions:
      - and:
        - condition: numeric_state # Allow only when startup_auto not active
          entity_id: "automation.therma_v_silent_on_at_startup_auto"  
          attribute: current  # Attribute is number of active instances of automation                  
          below: 1            # Below 1 means no active startup_auto instances
        - or:
          - and:
            - condition: state
              entity_id: switch.silent_mode_state
              state: 'off'
            - condition: time 
              after: input_datetime.silent_stop_time
              before: input_datetime.silent_start_time
          - condition: trigger
            id: temp_trig
    actions:
      - action: switch.turn_off
        target:
          entity_id: switch.therma_v_silent_mode

  - id: therma_v_silent_on_at_startup_auto
    alias: "Therma V Silent ON at startup auto"
    description: Turns on silent mode for some minutes after start-up
    mode: restart
    max_exceeded: silent
    triggers:
      - trigger: state
        entity_id: "binary_sensor.therma_v_compressor_state"
        from: "off"
        to: "on" # When compressor starts
      - trigger: state
        entity_id: "binary_sensor.therma_v_defrost_state"
        from: "on"
        to: "off" # Catch missed compressor restart  
    conditions:
      - condition: state 
        entity_id: switch.therma_v_heating_cooling_on_off
        state: "on" # And heating_cooling is on! otherwise RMC may crash
      - condition: state 
        entity_id: binary_sensor.therma_v_defrost_state
        state: "off" # And no defrost is active
      - condition: state 
        entity_id: input_boolean.silent_mode_startup
        state: "on" # And silent mode startup is ON
    actions:
      - variables:
          heat_target_temp: 29.5 # minimum temperature heating curve
          cool_target_temp: 17 # minimum temperature cooling curve
          timeout_minutes: 45 # time out after which wait for target is stopped
          wait_minutes: 20 # extra wait added after target reached for heating and timeout for DHW
      - action: switch.turn_on # Turn on silent mode
        target:
          entity_id: switch.therma_v_silent_mode
      - delay: # Wait for modbus registers to settle
          minutes: "1" 
      - choose: # Wait for start-up to finish 
          - conditions: # In case of DHW run
              - condition: state
                entity_id: binary_sensor.therma_v_dhw_heating_state
                state: "on"
            sequence:
              - wait_template: "{{ is_state('binary_sensor.therma_v_dhw_heating_state', 'off') }}"
                timeout: 
                  minutes: "{{ wait_minutes }}"
          - conditions: # In case of cooling run
              - condition: state
                entity_id: sensor.therma_v_outdoor_unit_state
                state: "1" # 0 off 1 cooling 2 heating
            sequence:
              - wait_template: "{{ (states('sensor.therma_v_inlet_temperature')|float(0)) < cool_target_temp }}"
                timeout: 
                  minutes: "{{ timeout_minutes }}" # Wait for target or timeout
              - delay: # In case of a heat run
                  minutes: "{{ wait_minutes }}" # Wait for X more minutes              
          - conditions: # In case of heating run
              - condition: state
                entity_id: sensor.therma_v_outdoor_unit_state
                state: "2" # 0 off 1 cooling 2 heating
            sequence:
              - wait_template: "{{ (states('sensor.therma_v_inlet_temperature')|float(0)) > heat_target_temp }}"
                timeout: 
                  minutes: "{{ timeout_minutes }}" # Wait for target or timeout
              - delay: 
                  minutes: "{{ wait_minutes }}" # Wait for X more minutes              
        default: # in case of unknown run
              - delay: 
                  minutes: "{{ wait_minutes }}" # Wait for X minutes      
      - choose: # Restore previous silent mode state
          - conditions:
            - and:
              - condition: state
                entity_id: switch.silent_mode_state
                state: 'off'
              - condition: time 
                after: input_datetime.silent_stop_time
                before: input_datetime.silent_start_time
            sequence:
              - action: switch.turn_off # If off switch off silent mode
                target:
                  entity_id: switch.therma_v_silent_mode

  - id: therma_v_silent_mode_off_auto
    alias: "Therma V Silent Mode OFF auto"
    description: "Turns off silent mode when heating/cooling is switched off"
    mode: single
    triggers:
      - trigger: state
        entity_id: "switch.therma_v_heating_cooling_on_off"
        from: "on"
        to: "off" # When heating/cooling switched off
      - trigger: time_pattern
        minutes: "/30"  # catch missed triggers
    conditions:
      - condition: state 
        entity_id: switch.therma_v_heating_cooling_on_off
        state: "off" # And heating_cooling is off!        
    actions:
      - action: switch.turn_off # Turn off silent mode
        target:
          entity_id: switch.silent_mode_state
      - action: input_boolean.turn_off # Turn off silent start
        target:
          entity_id: input_boolean.silent_mode_startup

  - id: therma_v_silent_mode_start_on_auto
    alias: "Therma V Silent Mode Start ON auto"
    description: "Turns on silent mode start when heating/cooling is switched on"
    mode: single
    triggers:
      - trigger: state
        entity_id: "switch.therma_v_heating_cooling_on_off"
        from: "off"
        to: "on" # When heating/cooling switched on
    conditions: []
    actions:
      - action: input_boolean.turn_on # Turn on silent start
        target:
          entity_id: input_boolean.silent_mode_startup