switch:
  # Template switch to used by the automationsas state memory
  # seperately from the real state of the relay which can be switched manually too
  - platform: template
    switches:
      dhw_booster_2_switch:
        friendly_name: "DHW booster 2 switch (S1)" 
        turn_on:
          action: switch.turn_on
          target:
            entity_id: switch.shelly_plug_s1
        turn_off:
          action: switch.turn_off
          target:
            entity_id: switch.shelly_plug_s1

template:
  # State of shelly switche S1 for Therma V DHW heater 2
  # which switches the DHW heater separately from the heatpump
  - binary_sensor: 
      - name: "Therma V DHW booster 2 state (S1)"
        state: >
          {{ is_state('switch.shelly_plug_s1', 'on') }}

automation:
  # switch on DHW heater when e-price incl. tax is negative
  # the DHW heater is switched with a separate parallel relay
  - id: dhw_e_price_negative_auto
    alias: "DHW e-price negative auto"
    description: Set DHW booster on when E-price is negative 
    mode: single
    triggers:
      - trigger: state
        entity_id: sensor.nord_pool_nl_current_prices_including_tax
    conditions:
      - condition: template
        value_template: "{{ (states('sensor.nord_pool_nl_current_prices_including_tax') | float(0) ) < 0 }}"
    actions:
      - action: switch.turn_on
        entity_id: switch.dhw_booster_2_switch
  # switch off DHW heater when e-price incl. tax is positive
  # Done every X minutes to make it robust for HA restarts
  # the DHW heater is switched with a separate parallel relay
  - id: dhw_e_price_positive_auto
    alias: "DHW e-price negative auto"
    description: Set DHW booster on when E-price is negative 
    mode: single
    triggers:
      - trigger: time_pattern
        minutes: "/5"
      - trigger: state
        entity_id: sensor.nord_pool_nl_current_prices_including_tax
    conditions:
      - condition: template
        value_template: "{{ (states('sensor.nord_pool_nl_current_prices_including_tax') | float(0) ) >= 0 }}"
    actions:
      - action: switch.turn_off
        entity_id: switch.dhw_booster_2_switch