# Set silent mode time interval
input_datetime:
  silent_start_time: # start time of silent mode add to UI
    name: Silent mode start time
    has_date: false
    has_time: true
  silent_stop_time: # stop time of silent mode add to UI
    name: Silent mode stop time
    has_date: false
    has_time: true

switch:
  # Switch which acts as state memory for the automations
  # So the automation knows the previous silent mode setting
  - platform: template
    switches:
      silent_mode_state:
        friendly_name: "Silent Mode State for automations" 
        turn_on:
          action: switch.turn_on
          target:
            entity_id: switch.therma_v_silent_mode
        turn_off:
          action: switch.turn_off
          target:
            entity_id: switch.therma_v_silent_mode

# Extra input which acts as state memory for silent mode at start-up
input_boolean:
  silent_mode_startup:
    name: "Silent Mode at Startup" 

automation:
  - id: therma_v_silent_on_based_on_temp_time_auto
    alias: "Therma V Silent ON based on temperature and time auto"
    description: Turns on silent mode at set time and when the temperature is high enough
    mode: single
    max_exceeded: silent
    triggers:
      - trigger: time
        at: input_datetime.silent_start_time
      - trigger: state
        entity_id: "sensor.therma_v_outside_temperature"
    conditions:
      - and:
        - condition: state
          entity_id: switch.therma_v_heating_cooling_on_off
          state: 'on' # Allow only when heating is on! otherwise RMC may crash
        - or:
          - condition: time 
            after: input_datetime.silent_start_time
            before: input_datetime.silent_stop_time
          - condition: numeric_state
            entity_id: "sensor.therma_v_outside_temperature"
            above: 8 # Silent mode off below 6 degrees for better defrosts
    actions:
      - action: switch.turn_on
        entity_id: switch.silent_mode_state

  - id: therma_v_silent_off_based_on_temp_time_auto
    alias: "Therma V Silent OFF based on temperature and time auto"
    description: Turns off silent mode when outside temp is too low respecting silent time window
    mode: single
    max_exceeded: silent
    triggers: # Time trigger to ensure that silent mode recovers to a safe state
      - trigger: time
        at: input_datetime.silent_stop_time
      - trigger: state
        entity_id: "sensor.therma_v_outside_temperature"
    conditions:
      - and:
        - condition: numeric_state # Allow only when startup_auto not active
          entity_id: "automation.therma_v_silent_on_at_startup"  
          attribute: current  # Attribute is number of active instances of automation                  
          below: 1            # Below 1 means n active startup_auto instances
        - condition: numeric_state
          entity_id: "sensor.therma_v_outside_temperature"
          below: 6 # Silent mode of below 6 degrees for better defrosts
        - condition: time 
          after: input_datetime.silent_stop_time
          before: input_datetime.silent_start_time
    actions:
      - action: switch.turn_off
        entity_id: switch.silent_mode_state

  - id: therma_v_silent_on_at_startup_auto
    alias: "Therma V Silent ON at startup auto"
    description: Turns on silent mode for some minutes after start-up
    mode: restart
    max_exceeded: silent
    triggers:
      - trigger: state
        entity_id: "binary_sensor.therma_v_compressor_state"
        from: "off"
        to: "on" # When compressor starts
      - trigger: state
        entity_id: "binary_sensor.therma_v_defrost_state"
        from: "on"
        to: "off" # Catch missed compressor restart  
    conditions:
      - condition: state 
        entity_id: switch.therma_v_heating_cooling_on_off
        state: "on" # And heating_cooling is on! otherwise RMC may crash
      - condition: state 
        entity_id: binary_sensor.therma_v_defrost_state
        state: "off" # And no defrost is active
      - condition: state 
        entity_id: input_boolean.silent_mode_startup
        state: "on" # And silent mode startup is ON
    actions:
      - action: switch.turn_on # Turn on silent mode
        entity_id: switch.therma_v_silent_mode
      - delay:
          minutes: 15 # Wait for startup to finish
      - choose: # Restore previous state of silent mode
          - conditions:
              - condition: state
                entity_id: switch.silent_mode_state
                state: "on"
            sequence:
              - action: switch.turn_on
                entity_id: switch.therma_v_silent_mode
        default:
          - action: switch.turn_off
            entity_id: switch.therma_v_silent_mode

  - id: therma_v_silent_switch_off_auto
    alias: "Therma V Silent switch OFF auto"
    description: "Turns off silent mode when heating/cooling is switched off"
    mode: single
    triggers:
      - trigger: state
        entity_id: "switch.therma_v_heating_cooling_on_off"
        from: "on"
        to: "off" # When heating/cooling switched off
      - trigger: time_pattern
        minutes: "/30"  # catch missed triggers
    conditions: []
    actions:
      - action: switch.turn_off # Turn on silent mode
        entity_id: switch.therma_v_silent_mode
      - action: input_boolean.turn_off
        entity_id: input_boolean.silent_mode_at_startup

  - id: therma_v_silent_start_on_auto
    alias: "Therma V Silent start ON auto"
    description: "Turns on silent mode start when heating/cooling is switched on"
    mode: single
    triggers:
      - trigger: state
        entity_id: "switch.therma_v_heating_cooling_on_off"
        from: "off"
        to: "on" # When heating/cooling switched off
    conditions: []
    actions:
      - action: input_boolean.turn_on
        entity_id: input_boolean.silent_mode_at_startup