#  https://forum.sessy.nl/home-assistant/quick-start-sessy-integreren-met-home-assistant/
#  https://forum.sessy.nl/home-assistant/scripts-om-sessys-aan-uit-te-zetten-vanuit-ha/

# STRATEGY [ POWER_STRATEGY_NOM, POWER_STRATEGY_ROI, POWER_STRATEGY_API, POWER_STRATEGY_IDLE, POWER_STRATEGY_SESSY_CONNECT, POWER_STRATEGY_ECO ]

rest_command:
  sessy_set_active_strategy:
    url: "http://{{host}}/api/v1/power/active_strategy"
    method: POST
    headers:
      authorization: "Basic {{auth | base64_encode }}"
    content_type: "application/json"
    payload: >-
      {{ { 
            "strategy": strategy
          }  | to_json }}

  # sessy_set_ns:
  #   url: "http://{{host}}/api/v1/eol/ns"
  #   method: POST
  #   headers:
  #     authorization: "Basic {{auth | base64_encode }}"
  #   content_type: "application/json"
  #   payload: >-
  #     {{  {
  #           "inverters": [
  #             {
  #               "inverter": inverter | int,
  #               "setpoint": setpoint | int 
  #             }
  #           ],
  #           "stop_override": stop_override | bool
  #         } | to_json }}

  sessy_set_power_setpoint:
    url: "http://{{host}}/api/v1/power/setpoint"
    method: POST
    headers:
      authorization: "Basic {{auth | base64_encode }}"
    content_type: "application/json"
    payload: >-
      {{  {
            "setpoint": setpoint | int
          } | to_json }}


  # sessy_set_power_setpoint_distributed:
  #   url: "http://{{host}}/api/v1/power/setpoint"
  #   method: POST
  #   headers:
  #     authorization: "Basic {{auth | base64_encode }}"
  #   content_type: "application/json"
  #   payload: >-
  #     {{  {
  #           "distributed": [
  #             {
  #               "inverter_index": 0,
  #               "setpoint": setpoint_l1
  #             },
  #             {
  #               "inverter_index": 1,
  #               "setpoint": setpoint_l2
  #             },
  #             {
  #               "inverter_index": 2,
  #               "setpoint": setpoint_l3
  #             }
  #           ]
  #         }  | to_json }}

script:
  sessy_set_strategy:
    sequence:
      - action: rest_command.sessy_set_active_strategy
        data:
          host: !secret sessy_url
          auth: !secret sessy_auth
          strategy: '{{strategy}}'

  sessy_set_power:
    sequence:
      - action: rest_command.sessy_set_power_setpoint
        data:
          host: !secret sessy_url
          auth: !secret sessy_auth
          setpoint: '{{setpoint}}'

  # sessy_set_power_distributed:
  #   sequence:
  #     - action: rest_command.sessy_set_power_setpoint_distributed
  #       data:
  #         host: !secret sessy_url
  #         auth: !secret sessy_auth
  #         setpoint_l1: '{{setpoint_l1}}'
  #         setpoint_l2: '{{setpoint_l2}}'
  #         setpoint_l3: '{{setpoint_l3}}'
 
input_select:
  sessy_strategy:
    name: "Sessy Strategy"
    icon: mdi:battery-cog
    options:
      - "POWER_STRATEGY_NOM"
      - "POWER_STRATEGY_ROI"
      - "POWER_STRATEGY_API"
      - "POWER_STRATEGY_IDLE"
      - "POWER_STRATEGY_SESSY_CONNECT"
      - "POWER_STRATEGY_ECO"

input_number:
  sessy_power_setpoint:
    name: "Sessy power setpoint"
    icon: mdi:transmission-tower
    min: -6000  # Maximaal laden
    max: 6000   # Maximaal ontladem
    step: 100
    unit_of_measurement: W
    mode: box
  # sessy_power_setpoint_inv1:
  #   name: "Sessy power setpoint L1"
  #   icon: mdi:transmission-tower
  #   min: -2000  # maximaal laden
  #   max: 2000   # maximaal ontladen
  #   step: 100
  #   unit_of_measurement: W
  #   mode: box
  # sessy_power_setpoint_inv2:
  #   name: "Sessy power setpoint L2"
  #   icon: mdi:transmission-tower
  #   min: -2000  # Maximaal laden
  #   max: 2000   # Maximaal ontladen
  #   step: 100
  #   unit_of_measurement: W
  #   mode: box
  # sessy_power_setpoint_inv3:
  #   name: "Sessy power setpoint L3"
  #   icon: mdi:transmission-tower
  #   min: -2000  # Maximaal laden
  #   max: 2000   # Maximaal ontladen
  #   step: 100
  #   unit_of_measurement: W
  #   mode: box

automation:
  - id: sessy_set_power_auto
    alias: "Sessy set power auto"
    description: "Set power on total system for strategy API"
    mode: restart
    trigger:
      - platform: state
        entity_id: input_number.sessy_power_setpoint
    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state not in ['unknown', 'unavailable'] }}"
    action:
      # auto set to api when slider is set to non zero
      - choose:
        - conditions:
            - condition: template
              value_template: "{{ (trigger.to_state.state | int | abs) > 0 }}"
          sequence:
            - action: input_select.select_option
              target:
                entity_id: input_select.sessy_strategy
              data:
                option: "POWER_STRATEGY_API"
            - delay: '00:00:05'
      - action: script.sessy_set_power
        data:
          setpoint: "{{ trigger.to_state.state | int }}"

    
  - id: sessy_synchronise_active_strategy_auto
    alias: "Sessy synchronise active strategy auto"
    description: "Synchronizes input select with sessy"
    mode: restart
    trigger:
      - platform: state
        entity_id: sensor.sessy_active_strategy
    condition:
      - condition: template
        # Voorkom fouten bij opstarten
        value_template: "{{ trigger.to_state.state not in ['unknown', 'unavailable'] }}"
      - condition: template
        # Pas de input_select ALLEEN aan als deze momenteel iets anders aangeeft dan de sensor
        value_template: "{{ states('input_select.sessy_strategy') != trigger.to_state.state }}"
    action:
      - action: input_select.select_option
        target:
          entity_id: input_select.sessy_strategy
        data:
          option: "{{ trigger.to_state.state }}"
 
  - id: sessy_set_active_strategy_auto
    alias: "Sessy set active strategy auto"
    description: "Sets Sessy active strategy when input select changes"
    mode: restart
    trigger:
      - platform: state
        entity_id: input_select.sessy_strategy
    condition:
      - condition: template
        # Voorkomt dat de automatisering triggert bij een Home Assistant herstart (wanneer status 'unknown' of 'unavailable' is)
        value_template: "{{ trigger.to_state.state not in ['unknown', 'unavailable'] }}"
    action:
      - action: script.sessy_set_strategy
        data:
          strategy: "{{ trigger.to_state.state }}"
      # auto set to slider to 0 when strategy is non api
      - choose:
        - conditions:
            - condition: template
              value_template: "{{ not is_state('input_select.sessy_strategy','POWER_STRATEGY_API') }}"
          sequence:
            - action: input_number.set_value
              target:
                entity_id: input_number.sessy_power_setpoint
              data:
                value: 0

    
  # - id: sessy_set_power_inv1_auto
  #   alias: "Sessy set power inv1 auto"
  #   description: "Set power on inverter 1 for strategy API"
  #   mode: restart
  #   trigger:
  #     - platform: state
  #       entity_id: input_number.sessy_power_setpoint_inv1
  #   condition:
  #     - condition: template
  #       value_template: "{{ trigger.to_state.state not in ['unknown', 'unavailable'] }}"
  #   action:
  #     - action: script.sessy_set_power_distributed
  #       data:
  #         # inverter: 1 
  #         setpoint_l1: "{{ trigger.to_state.state | int }}"
  #         setpoint_l2: "{{ states('input_number.sessy_power_setpoint_inv2') | int }}"
  #         setpoint_l3: "{{ states('input_number.sessy_power_setpoint_inv3') | int }}"
  #         # stop_override: >
  #         #   {% if (trigger.to_state.state|int==0) and (states('input_number.sessy_power_setpoint_inv2')|int==0)  and (states('input_number.sessy_power_setpoint_inv3')|int==0) %} 
  #         #       {{ true }}
  #         #   {% else %}
  #         #       {{ false }}
  #         #   {% endif %}            


  # - id: sessy_set_power_inv2_auto
  #   alias: "Sessy set power inv2 auto"
  #   description: "Set power on inverter 2 for strategy API"
  #   mode: restart
  #   trigger:
  #     - platform: state
  #       entity_id: input_number.sessy_power_setpoint_inv2
  #   condition:
  #     - condition: template
  #       value_template: "{{ trigger.to_state.state not in ['unknown', 'unavailable'] }}"
  #   action:
  #     - action: script.sessy_set_power_distributed
  #       data:
  #         # inverter: 2 
  #         setpoint_l1: "{{ states('input_number.sessy_power_setpoint_inv1') | int }}"
  #         setpoint_l2: "{{ trigger.to_state.state | int }}"
  #         setpoint_l3: "{{ states('input_number.sessy_power_setpoint_inv3') | int }}"
  #         # stop_override: >
  #         #   {% if (states('input_number.sessy_power_setpoint_inv1')|int==0) and (trigger.to_state.state|int==0) and (states('input_number.sessy_power_setpoint_inv3')|int==0)  %} 
  #         #       {{ true }}
  #         #   {% else %}
  #         #       {{ false }}
  #         #   {% endif %}  
    

  # - id: sessy_set_power_inv3_auto
  #   alias: "Sessy set power inv3 auto"
  #   description: "Set power on inverter 3 for strategy API"
  #   mode: restart
  #   trigger:
  #     - platform: state
  #       entity_id: input_number.sessy_power_setpoint_inv3
  #   condition:
  #     - condition: template
  #       value_template: "{{ trigger.to_state.state not in ['unknown', 'unavailable'] }}"
  #   action:
  #     - action: script.sessy_set_power_distributed
  #       data:
  #         # inverter: 3 
  #         setpoint_l1: "{{ states('input_number.sessy_power_setpoint_inv1') | int }}"
  #         setpoint_l2: "{{ states('input_number.sessy_power_setpoint_inv2') | int }}"
  #         setpoint_l3: "{{ trigger.to_state.state | int }}"
  #         # stop_override: >
  #         #   {% if (states('input_number.sessy_power_setpoint_inv1')|int==0) and (states('input_number.sessy_power_setpoint_inv2')|int==0) and (trigger.to_state.state|int==0) %} 
  #         #       {{ true }}
  #         #   {% else %}
  #         #       {{ false }}
  #         #   {% endif %}  